swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts/{accountId}/transactions:
    get:
      tags:
        - Transaction Module
      summary: List Account Transactions
      description: Retrieves a list of transactions for a specified account, including Date, Description, Amount, and Balance.
      parameters:
        - in: path
          name: accountId
          type: string
          required: true
          description: Unique identifier of the account
      produces:
        - application/json
      responses:
        '200':
          description: A list of transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid parameters
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  /accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Transaction Details
      description: Retrieves details of a specific transaction, including Transaction Type, Category, and Notes.
      parameters:
        - in: path
          name: accountId
          type: string
          required: true
          description: Unique identifier of the account
        - in: path
          name: transactionId
          type: string
          required: true
          description: Unique identifier of the transaction
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid parameters
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

  /accounts/{accountId}/transactions/{transactionId}/edit:
    put:
      tags:
        - Transaction Module
      summary: Edit Transaction Details
      description: Updates the Category and Notes of a specific transaction.
      parameters:
        - in: path
          name: accountId
          type: string
          required: true
          description: Unique identifier of the account
        - in: path
          name: transactionId
          type: string
          required: true
          description: Unique identifier of the transaction
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                description: New category for the transaction
              notes:
                type: string
                description: New notes for the transaction
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details updated successfully
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: double
        description: Amount of money transacted
      balance:
        type: number
        format: double
        description: Account balance after the transaction

  TransactionDetails:
    type: object
    properties:
      transactionType:
        type: string
        description: Type of the transaction (e.g., electronic, check)
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: Notes associated with the transaction
